"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))  
HERE = os.path.join(HERE, '../') 
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


BROKER_URL = 'django://localhost:8000//'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_TIMEZONE = 'Asia/Shanghai'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hsm-s0lc!1m_mz!7&dzz!x1&7(@%yg&bf-_4c0$sic2!y0r=iv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS= True


ALLOWED_HOSTS = ['*']
SECRET_KEY='=tx*p*-uxtv4wt7wk(jq26k*b=vh3rwvwc%6+)3x3d1ycop_p!'
LINE_CHANNEL_ACCESS_TOKEN = "RslI2bVqAZpuagawWX/trCi3Kbccahs99nKAtA5uQin1QUlhTEssDJq0R0p17vYf91OoJHcDxMJZKc6AanZYap+Ad0ESpT2rlhQMK/NUohIbuuzJfEd1MJxLE1ScdZETGTarWc9Zs6De8YCKcJGQmgdB04t89/1O/w1cDnyilFU="
LINE_CHANNEL_SECRET = "c1ac023d93a0f539fe1f8e50afed5125"

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kombu.transport.django',
    'users',
    'trips',
    'djcelery',
    'corsheaders',
    'bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'template').replace('\\','/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Additional locations of static files  
STATICFILES_DIRS = (  
    # Put strings here, like "/home/html/static" or "C:/www/django/static".  
    # Always use forward slashes, even on Windows.  
    # Don't forget to use absolute paths, not relative paths.  
    os.path.join(os.path.dirname(__file__), '..', 'static').replace('\\','/'),  
    os.path.join('static'),  
)  

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',#'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),#os.path.join(BASE_DIR, 'db.sqlite3'),
        #'USER': 'root',                       # Not used with sqlite3.
        #'PASSWORD': '104590454',               # Not used with sqlite3.
        #'HOST': '',                           # Set to empty string for localhost. Not used with sqlite3.
        #'PORT': '',                           # Set to empty string for default. Not used with sqlite3.
    }
}

CRONJOBS = [
#     #('*/1 * * * *', 'django.core.management.call_command', ['crontab']),#for all file
     ('*/1 * * * *', 'trips.crontab.RunForSecond')#ten second once
#     #('*/1 * * * *', 'trips.models.BittrexForSecond'),
    
]
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = False

USE_TZ = False
DATETIME_FORMAT='Y-m-d H:i:s'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

#LOGIN_REDIRECT_URL = "/index/"