# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
