# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_coin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coin',
            new_name='CoinTable',
        ),
    ]
