# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_auto_20180316_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerBTCTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=100)),
                ('bid', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='BTCTable',
            new_name='BittrexBTCTable',
        ),
    ]
