# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20180316_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TickerBTCTable',
            new_name='CexBTCTable',
        ),
    ]
