# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_binancebtctable_bitfinexbtctable_cryptopiabtctable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancebtctable',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bitfinexbtctable',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bittrexbtctable',
            name='ask',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bittrexbtctable',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bittrexbtctable',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cexbtctable',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cryptopiabtctable',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
