# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_auto_20180317_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancebtctable',
            name='ask',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='binancebtctable',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bitfinexbtctable',
            name='ask',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bitfinexbtctable',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cexbtctable',
            name='ask',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cexbtctable',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cryptopiabtctable',
            name='ask',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cryptopiabtctable',
            name='bid',
            field=models.FloatField(default=0),
        ),
    ]
