# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0015_auto_20180528_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transectionA', models.CharField(max_length=64)),
                ('transectionB', models.CharField(max_length=64)),
                ('cointype', models.CharField(max_length=64)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiBi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transectionA', models.CharField(max_length=64)),
                ('transectionB', models.CharField(max_length=64)),
                ('cointypeA', models.CharField(max_length=64)),
                ('cointypeB', models.CharField(max_length=64)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bittrexmoney', models.FloatField(default=0.0)),
                ('Binancemoney', models.FloatField(default=0.0)),
                ('CexBTC', models.FloatField(default=0.0)),
                ('BittrexBTC', models.FloatField(default=0.0)),
                ('BinanceBTC', models.FloatField(default=0.0)),
                ('Cexmoney', models.FloatField(default=0.0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransectionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee', models.FloatField(default=0.0)),
                ('BidTransection', models.CharField(max_length=100)),
                ('AskTransection', models.CharField(max_length=100)),
                ('Bid', models.FloatField(default=0.0)),
                ('Ask', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField()),
                ('flag', models.CharField(default=b'0', max_length=1)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
