# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-28 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0016_apple_bibi_purse_transectionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgTypeByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head', models.CharField(max_length=64)),
                ('Foot', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
