# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_binanceethtable_bitfinexethtable_bittrexethtable_cexethtable_cryptopiaethtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algtypebyuser',
            name='userID',
            field=models.IntegerField(max_length=20),
        ),
    ]
