# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_auto_20180922_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgTypeByUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(max_length=20)),
                ('Head', models.CharField(max_length=64)),
                ('Foot', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
