# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_linebot_identifyingcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebot',
            name='UserId',
            field=models.CharField(max_length=20),
        ),
    ]
