# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-27 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180910_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebot',
            name='LineId',
            field=models.CharField(max_length=50),
        ),
    ]
