# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_botrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opinion', models.CharField(default='SOME STRING', max_length=512)),
                ('LineId', models.CharField(max_length=50)),
            ],
        ),
    ]
