# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='money',
            new_name='Binancemoney',
        ),
        migrations.AddField(
            model_name='user',
            name='Bittrexmoney',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='Cexmoney',
            field=models.FloatField(default=0.0),
        ),
    ]
