# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180601_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BinanceBTC',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='BittrexBTC',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='CexBTC',
            field=models.FloatField(default=0.0),
        ),
    ]
