# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180927_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BinanceBTC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Binancemoney',
        ),
        migrations.AddField(
            model_name='user',
            name='BitfinexBTC',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='Bitfinexmoney',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='CrytopiaBTC',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='Crytopiamoney',
            field=models.FloatField(default=0.0),
        ),
    ]
