# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180928_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CrytopiaBTC',
            new_name='CryptopiaBTC',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Crytopiamoney',
            new_name='Cryptopiamoney',
        ),
    ]
